(in-package :fake-cl)

(defvar *first-name* '(
                       "Enzo"
                       "Lucas"
                       "Mathis"
                       "Nathan"
                       "Thomas"
                       "Hugo"
                       "Théo"
                       "Tom"
                       "Louis"
                       "Raphaël"
                       "Clément"
                       "Léo"
                       "Mathéo"
                       "Maxime"
                       "Alexandre"
                       "Antoine"
                       "Yanis"
                       "Paul"
                       "Baptiste"
                       "Alexis"
                       "Gabriel"
                       "Arthur"
                       "Jules"
                       "Ethan"
                       "Noah"
                       "Quentin"
                       "Axel"
                       "Evan"
                       "Mattéo"
                       "Romain"
                       "Valentin"
                       "Maxence"
                       "Noa"
                       "Adam"
                       "Nicolas"
                       "Julien"
                       "Mael"
                       "Pierre"
                       "Rayan"
                       "Victor"
                       "Mohamed"
                       "Adrien"
                       "Kylian"
                       "Sacha"
                       "Benjamin"
                       "Léa"
                       "Clara"
                       "Manon"
                       "Chloé"
                       "Camille"
                       "Ines"
                       "Sarah"
                       "Jade"
                       "Lola"
                       "Anaïs"
                       "Lucie"
                       "Océane"
                       "Lilou"
                       "Marie"
                       "Eva"
                       "Romane"
                       "Lisa"
                       "Zoe"
                       "Julie"
                       "Mathilde"
                       "Louise"
                       "Juliette"
                       "Clémence"
                       "Célia"
                       "Laura"
                       "Lena"
                       "Maëlys"
                       "Charlotte"
                       "Ambre"
                       "Maeva"
                       "Pauline"
                       "Lina"
                       "Jeanne"
                       "Lou"
                       "Noémie"
                       "Justine"
                       "Louna"
                       "Elisa"
                       "Alice"
                       "Emilie"
                       "Carla"
                       "Maëlle"
                       "Alicia"
                       "Mélissa"))

(defvar *last-name* '(
                      "Martin"
                      "Bernard"
                      "Dubois"
                      "Thomas"
                      "Robert"
                      "Richard"
                      "Petit"
                      "Durand"
                      "Leroy"
                      "Moreau"
                      "Simon"
                      "Laurent"
                      "Lefebvre"
                      "Michel"
                      "Garcia"
                      "David"
                      "Bertrand"
                      "Roux"
                      "Vincent"
                      "Fournier"
                      "Morel"
                      "Girard"
                      "Andre"
                      "Lefevre"
                      "Mercier"
                      "Dupont"
                      "Lambert"
                      "Bonnet"
                      "Francois"
                      "Martinez"
                      "Legrand"
                      "Garnier"
                      "Faure"
                      "Rousseau"
                      "Blanc"
                      "Guerin"
                      "Muller"
                      "Henry"
                      "Roussel"
                      "Nicolas"
                      "Perrin"
                      "Morin"
                      "Mathieu"
                      "Clement"
                      "Gauthier"
                      "Dumont"
                      "Lopez"
                      "Fontaine"
                      "Chevalier"
                      "Robin"
                      "Masson"
                      "Sanchez"
                      "Gerard"
                      "Nguyen"
                      "Boyer"
                      "Denis"
                      "Lemaire"
                      "Duval"
                      "Joly"
                      "Gautier"
                      "Roger"
                      "Roche"
                      "Roy"
                      "Noel"
                      "Meyer"
                      "Lucas"
                      "Meunier"
                      "Jean"
                      "Perez"
                      "Marchand"
                      "Dufour"
                      "Blanchard"
                      "Marie"
                      "Barbier"
                      "Brun"
                      "Dumas"
                      "Brunet"
                      "Schmitt"
                      "Leroux"
                      "Colin"
                      "Fernandez"
                      "Pierre"
                      "Renard"
                      "Arnaud"
                      "Rolland"
                      "Caron"
                      "Aubert"
                      "Giraud"
                      "Leclerc"
                      "Vidal"
                      "Bourgeois"
                      "Renaud"
                      "Lemoine"
                      "Picard"
                      "Gaillard"
                      "Philippe"
                      "Leclercq"
                      "Lacroix"
                      "Fabre"
                      "Dupuis"
                      "Olivier"
                      "Rodriguez"
                      "Da silva"
                      "Hubert"
                      "Louis"
                      "Charles"
                      "Guillot"
                      "Riviere"
                      "Le gall"
                      "Guillaume"
                      "Adam"
                      "Rey"
                      "Moulin"
                      "Gonzalez"
                      "Berger"
                      "Lecomte"
                      "Menard"
                      "Fleury"
                      "Deschamps"
                      "Carpentier"
                      "Julien"
                      "Benoit"
                      "Paris"
                      "Maillard"
                      "Marchal"
                      "Aubry"
                      "Vasseur"
                      "Le roux"
                      "Renault"
                      "Jacquet"
                      "Collet"
                      "Prevost"
                      "Poirier"
                      "Charpentier"
                      "Royer"
                      "Huet"
                      "Baron"
                      "Dupuy"
                      "Pons"
                      "Paul"
                      "Laine"
                      "Carre"
                      "Breton"
                      "Remy"
                      "Schneider"
                      "Perrot"
                      "Guyot"
                      "Barre"
                      "Marty"
                      "Cousin"))

(defvar *phone-number* '("+33 6~a~a~a~a~a~a~a~a"
                         "+33 7~a~a~a~a~a~a~a~a"))

(defvar *free-email* '(
                       "gmail.com"
                       "yahoo.fr"
                       "hotmail.fr"))

(defvar *paris-metros* '(
                         "Wagram"
                         "Voltaire"
                         "Volontaires"
                         "Villiers"
                         "Villejuif"
                         "Villejuif"
                         "Villejuif"
                         "Victor Hugo"
                         "Verdun-Sud"
                         "Vavin"
                         "Vaugirard"
                         "Varenne"
                         "Vaneau"
                         "Tuileries"
                         "Trocadéro"
                         "Trinité"
                         "Tolbiac"
                         "Ternes"
                         "Temple"
                         "Télégraphe"
                         "Sully – Morland"
                         "Strasbourg – Saint-Denis"
                         "Stalingrad"
                         "Solférino"
                         "Simplon"
                         "Sèvres"
                         "Sèvres – Babylone"
                         "Sentier"
                         "Ségur"
                         "Saint-Sulpice"
                         "Saint-Sébastien – Froissart"
                         "Saint-Placide"
                         "Saint-Philippe du Roule"
                         "Saint-Paul"
                         "Saint-Michel"
                         "Saint-Marcel"
                         "Saint-Mandé"
                         "Saint-Lazare"
                         "Saint-Jacques"
                         "Saint-Germain-des-Prés"
                         "Saint-Georges"
                         "Saint-François-Xavier"
                         "Saint-Fargeau"
                         "Saint-Denis – Université"
                         "Saint-Denis – Porte de Paris"
                         "Saint-Augustin"
                         "Saint-Ambroise"
                         "Rue Saint-Maur"
                         "Rue du Bac"
                         "Rue des Boulets"
                         "Rue de la Pompe"
                         "Rome"
                         "Robespierre"
                         "Riquet"
                         "Richelieu – Drouot"
                         "Richard-Lenoir"
                         "Reuilly – Diderot"
                         "République"
                         "Rennes"
                         "Réaumur – Sébastopol"
                         "Raspail	Raspail"
                         "Ranelagh	Ranelagh"
                         "Rambuteau	Rambuteau"
                         "Quatre-Septembre	Quatre-Septembre"
                         "Quai de la Rapée	Quai de la Rapée"
                         "Quai de la Gare	Quai de la Gare"
                         "Pyrénées	Pyrénées"
                         "Pyramides	Pyramides"
                         "Pré Saint-Gervais	Pré Saint-Gervais"
                         "Porte Maillot	Porte Maillot"
                         "Porte Dorée	Porte Dorée"
                         "Porte des Lilas	Porte des Lilas"
                         "Porte de Vincennes	Porte de Vincennes"
                         "Porte de Versailles	Porte de Versailles"
                         "Porte de Vanves	Porte de Vanves"
                         "Porte de Saint-Ouen	Porte de Saint-Ouen"
                         "Porte de Saint-Cloud	Porte de Saint-Cloud"
                         "Porte de Pantin	Porte de Pantin"
                         "Porte de Montreuil	Porte de Montreuil"
                         "Porte de la Villette	Porte de la Villette"
                         "Porte de la Chapelle	Porte de la Chapelle"
                         "Porte de Clignancourt	Porte de Clignancourt"
                         "Porte de Clichy	Porte de Clichy"
                         "Porte de Choisy	Porte de Choisy"
                         "Porte de Charenton	Porte de Charenton"
                         "Porte de Champerret	Porte de Champerret"
                         "Porte de Bagnolet	Porte de Bagnolet"
                         "Porte Dauphine	Porte Dauphine"
                         "Porte d'Orléans	Porte d’Orléans"
                         "Porte d'Ivry	Porte d’Ivry"
                         "Porte d'Italie	Porte d’Italie"
                         "Porte d'Auteuil	Porte d’Auteuil"
                         "Pont Neuf	Pont Neuf"
                         "Pont Marie	Pont Marie"
                         "Pont de Sèvres	Pont de Sèvres"
                         "Pont de Neuilly	Pont de Neuilly"
                         "Pont de Levallois – Bécon	Pont de Levallois – Bécon"
                         "Poissonnière	Poissonnière"
                         "Pointe du Lac	Pointe du Lac	PTL	8	1	Créteil	8 October 2011	Stade Dominique Duvauchelle"
                         "Plaisance	Plaisance"
                         "Place Monge	Place Monge"
                         "Place des Fêtes	Place des Fêtes"
                         "Place de Clichy	Place de Clichy"
                         "Place d'Italie	Place d’Italie"
                         "Pigalle	Pigalle"
                         "Pierre et Marie Curie	Pierre et Marie Curie"
                         "Picpus	Picpus"
                         "Philippe Auguste	Philippe Auguste"
                         "Pernety	Pernety"
                         "Pereire	Pereire"
                         "Père Lachaise	Père Lachaise"
                         "Pelleport	Pelleport"
                         "Pasteur	Pasteur"
                         "Passy	Pasteur"
                         "Parmentier	Parmentier"
                         "Palais Royal – Musée du Louvre	Palais Royal – Musée du Louvre"
                         "Ourcq	Ourcq	"
                         "Opéra	Opéra	"
                         "Olympiades	Olympiades	"
                         "Odéon"
                         "Oberkampf"
                         "Notre-Dame-des-Champs"
                         "Notre-Dame-de-Lorette"
                         "Nationale"
                         "Nation"
                         "Mouton-Duvernet"
                         "Montparnasse – Bienvenüe"
                         "Montgallet	Montgallet	12-03	8	1	12	5 May 1931	Promenade plantée"
                         "Monceau	Miromesnil"
                         "Miromesnil	Miromesnil"
                         "Mirabeau	Mirabeau"
                         "Michel-Ange – Molitor	Michel-Ange – Molitor"
                         "Michel-Ange – Auteuil	Michel-Ange – Auteuil"
                         "Michel Bizot	Michel Bizot"
                         "Ménilmontant	Ménilmontant"
                         "Maubert-Mutualité	Maubert-Mutualité"
                         "Marx Dormoy	Marx Dormoy"
                         "Marcel Sembat"
                         "Marcadet – Poissonniers"
                         "Maraîchers"
                         "Malesherbes"
                         "Malakoff – Rue Étienne Dolet"
                         "Malakoff – Plateau de Vanves"
                         "Maisons-Alfort – Stade"
                         "Maisons-Alfort – Les Juilliottes"
                         "Maison Blanche"
                         "Mairie des Lilas"
                         "Mairie de Saint-Ouen"
                         "Mairie de Montrouge"
                         "Mairie de Montreuil"
                         "Mairie de Clichy"
                         "Mairie d'Ivry"
                         "Mairie d'Issy"
                         "Madeleine"
                         "Mabillon"
                         "Louvre – Rivoli"
                         "Lourmel"
                         "Louise Michel"
                         "Louis Blanc"
                         "Liège"
                         "Liberté"
                         "Les Sablons"
                         "Les Halles"
                         "Les Gobelins"
                         "Les Courtilles"
                         "Les Agnettes"
                         "Ledru-Rollin"
                         "Le Peletier"
                         "Le Kremlin-Bicêtre"
                         "Laumière"
                         "Lamarck – Caulaincourt"
                         "La Tour-Maubourg"
                         "La Muette"
                         "La Motte-Picquet – Grenelle"
                         "La Fourche"
                         "La Défense – Grande Arche"
                         "La Courneuve – 8 Mai 1945"
                         "La Chapelle"
                         "Kléber"
                         "Jussieu"
                         "Jules Joffrin"
                         "Jourdain"
                         "Javel – André Citroën"
                         "Jaurès"
                         "Jasmin"
                         "Jacques Bonsergent"
                         "Invalides"
                         "Iéna"
                         "Hôtel de Ville"
                         "Hoche"
                         "Havre – Caumartin"
                         "Guy Môquet"
                         "Grands Boulevards"
                         "Goncourt"
                         "Glacière"
                         "George V"
                         "Garibaldi"
                         "Gare du Nord"
                         "Gare de Lyon"
                         "Gare de l'Est"
                         "Gare d'Austerlitz"
                         "Gambetta"
                         "Gallieni"
                         "Gaîté"
                         "Gabriel Péri"
                         "Front Populaire"
                         "Franklin D. Roosevelt"
                         "Fort d'Aubervilliers"
                         "Filles du Calvaire"
                         "Félix Faure"
                         "Falguière"
                         "Faidherbe – Chaligny"
                         "Exelmans"
                         "Europe"
                         "Étienne Marcel"
                         "Esplanade de La Défense"
                         "Église de Pantin"
                         "Église d'Auteuil"
                         "Edgar Quinet"
                         "École Vétérinaire de Maisons-Alfort"
                         "École Militaire"
                         "Duroc"
                         "Dupleix"
                         "Dugommier"
                         "Denfert-Rochereau"
                         "Daumesnil"
                         "Danube"
                         "Croix de Chavaux"
                         "Crimée"
                         "Créteil – Université"
                         "Créteil – Préfecture"
                         "Créteil – L'Échat"
                         "Couronnes"
                         "Courcelles"
                         "Cour Saint-Émilion"
                         "Corvisart"
                         "Corentin Celton"
                         "Corentin Cariou"
                         "Convention"
                         "Concorde"
                         "Commerce"
                         "Colonel Fabien"
                         "Cluny – La Sorbonne"
                         "Cité"
                         "Chevaleret"
                         "Chemin Vert"
                         "Chaussée d'Antin – La Fayette"
                         "Châtillon – Montrouge"
                         "Montrouge	9 November 1976	"
                         "Châtelet"
                         "Château Rouge"
                         "Château-Landon"
                         "Château de Vincennes"
                         "Château d'Eau"
                         "Charonne"
                         "Charles Michels"
                         "Charles de Gaulle – Étoile"
                         "Charenton – Écoles"
                         "Chardon Lagache"
                         "Champs-Élysées – Clemenceau"
                         "Censier – Daubenton"
                         "Carrefour Pleyel"
                         "Cardinal Lemoine"
                         "Campo Formio"
                         "Cambronne"
                         "Cadet"
                         "Buzenval"
                         "Buttes Chaumont"
                         "Brochant"
                         "Bréguet – Sabin"
                         "Bourse"
                         "Boulogne – Pont de Saint-Cloud"
                         "Boulogne – Jean Jaurès"
                         "Boucicaut"
                         "Botzaris"
                         "Bonne Nouvelle"
                         "Bolivar"
                         "Boissière"
                         "Bobigny – Pantin – Raymond Queneau"
                         "Bobigny – Pablo Picasso"
                         "Blanche"
                         "Bir-Hakeim"
                         "Billancourt"
                         "Bibliothèque François Mitterrand"
                         "Bercy"
                         "Bérault"
                         "Belleville"
                         "Bel-Air"
                         "Bastille"
                         "Basilique de Saint-Denis"
                         "Barbès – Rochechouart"
                         "Balard"
                         "Bagneux"
                         "Avron"
                         "Avenue Émile Zola"
                         "Aubervilliers – Pantin – Quatre Chemins"
                         "Assemblée Nationale"
                         "Arts et Métiers"
                         "Argentine"
                         "Anvers"
                         "Anatole France"
                         "Alma – Marceau"
                         "Alexandre Dumas"
                         "Alésia"
                         "Abbesses"))
