(defpackage :fake-cl.medecin
  (:use :common-lisp)
  (:export *specialities*))
        

(in-package :fake-cl.medecin)

(defvar *specialities* '("allergologie"
                         "andrologie"
                         "anesthésiologie"
                         "cardiologie"
                         "chirurgie"
                         "chirurgie cardiaque"
                         "chirurgie plastique, reconstructive et esthétique"
                         "chirurgie générale"
                         "chirurgie gynécologique"
                         "chirurgie maxillo-faciale"
                         "chirurgie oculaire"
                         "chirurgie orale"
                         "chirurgie pédiatrique"
                         "chirurgie thoracique"
                         "chirurgie vasculaire"
                         "chirurgie viscérale"
                         "neurochirurgie"
                         "dermatologie"
                         "endocrinologie"
                         "gastro-entérologie"
                         "gériatrie"
                         "gynécologie"
                         "hématologie"
                         "hépatologie"
                         "immunologie"
                         "infectiologie"
                         "médecine aiguë"
                         "médecine du travail"
                         "médecine d'urgence"
                         "médecine générale"
                         "médecine interne"
                         "médecine nucléaire"
                         "médecine palliative"
                         "médecine physique et de réadaptation"
                         "médecine préventive"
                         "néonatologie"
                         "néphrologie"
                         "neurologie"
                         "obstétrique"
                         "odontologie"
                         "oncologie"
                         "ophtalmologie"
                         "orthopédie"
                         "otorhinolaryngologie"
                         "pédiatrie"
                         "pneumologie"
                         "podologie"
                         "psychiatrie"
                         "radiologie"
                         "radiothérapie"
                         "rhumatologie"
                         "urologie"))
